const ActionTypes = {
    TOGGLE_OPEN_ADD_DB_FORM: "TOGGLE_OPEN_ADD_DB_FORM",
    OPEN_ADD_DB_FORM: "OPEN_ADD_DB_FORM",
    ADD_DATABASE: "ADD_DATABASE",
    DELETE_DATABASE: "DELETE_DATABASE",
    UPDATE_DATABASE: "UPDATE_DATABASE",
    SET_UPDATE_DATABASE_ID: "SET_UPDATE_DATABASE_ID",

    SET_CURRENT_SELECTED_DB: "SET_CURRENT_SELECTED_DB",
    CHANGE_SEARCH_DBLIST_TEXT: "CHANGE_SEARCH_DBLIST_TEXT",
}

export default ActionTypes