import Head from 'next/head'
import {Input, Modal} from 'antd';

import {BiPlus} from "react-icons/bi";
import AddDatabase from "../components/Redis/AddDatabase";
import {useDispatch, useSelector} from "react-redux";
import {fetchDatabases, toggleOpenDbForm} from "../actions/redisTools";

import ListDatabase from "../components/Redis/ListDatabase";

import RedisToolsLayout from "../layout/RedisToolsLayout"
import ActionTypes from "../store/actionTypes";
import {useEffect, useState} from "react";
import Header from "../components/Redis/Header";

const {Search} = Input;

export default function Home() {

    const dispatch = useDispatch()


    const {isOpenAddDbForm, databases} = useSelector(state => state.redisTools)
    const [isLoaded, setLoaded] = useState(false)

    useEffect(() => {
        setLoaded(false)
        dispatch(fetchDatabases(function (err){
            setLoaded(true)
        }))
    }, [])


    function onSearch(value) {
        dispatch({
            type: ActionTypes.CHANGE_SEARCH_DBLIST_TEXT,
            payload: value
        })
    }

    function closeAddDatabaseForm(){
        dispatch({
            type: ActionTypes.CLOSE_ADD_DB_FORM,
        })
    }



    return (
        <RedisToolsLayout>
            <Head>
                <title>My Redis database</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <Header/>
                <div className="top-bar-space"></div>

                <div className="" style={{marginLeft: "60px", marginTop: "10px"}}>
                    <div className="flex justify-between">
                        <div style={{margin: "10px"}}>
                            <button onClick={() => dispatch(toggleOpenDbForm())}
                                    className="flex items-center justify-center default_button">
                                <BiPlus/>
                                Add Database
                            </button>
                        </div>

                        <div style={{margin: "10px"}}>
                            <Search className="custom-input" placeholder="Database List Search" onSearch={onSearch}
                                    style={{width: 200}}/>
                        </div>
                    </div>


                    <div style={{marginTop: "12px", minHeight: "500px"}} >

                       <ListDatabase isLoaded={isLoaded}/>


                        <Modal className="add-database-modal" open={isOpenAddDbForm} footer={null} onCancel={closeAddDatabaseForm}>
                            <div className={`add-db-form ${isOpenAddDbForm ? "open" : "hide"}`}>
                                <AddDatabase isOpenAddDbForm={isOpenAddDbForm}/>
                            </div>
                        </Modal>

                    </div>

                </div>
            </div>
        </RedisToolsLayout>
    )
}
